// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuTY52CoML9HZyk5Zwvri1so8p41fJEUQ',
    appId: '1:1085587191214:web:c21f3846fcacf0347cc43f',
    messagingSenderId: '1085587191214',
    projectId: 'tstorefirebase-d4d75',
    authDomain: 'tstorefirebase-d4d75.firebaseapp.com',
    storageBucket: 'tstorefirebase-d4d75.appspot.com',
    measurementId: 'G-MB2V91VEGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7uzkII4ynHNzUEj3BAluBiK0gyvd_es',
    appId: '1:1085587191214:android:bd21d960e758613c7cc43f',
    messagingSenderId: '1085587191214',
    projectId: 'tstorefirebase-d4d75',
    storageBucket: 'tstorefirebase-d4d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6R5spbQoXXzeTSJtGaS4THUqkwmZ47Uk',
    appId: '1:1085587191214:ios:32208430dd1008db7cc43f',
    messagingSenderId: '1085587191214',
    projectId: 'tstorefirebase-d4d75',
    storageBucket: 'tstorefirebase-d4d75.appspot.com',
    androidClientId: '1085587191214-krj853hg2tutradash8gu387sgtlg4ba.apps.googleusercontent.com',
    iosClientId: '1085587191214-0j69hoi8oidfte0jjuf2s6t4ga0ac71p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6R5spbQoXXzeTSJtGaS4THUqkwmZ47Uk',
    appId: '1:1085587191214:ios:bd6d30d97656c0047cc43f',
    messagingSenderId: '1085587191214',
    projectId: 'tstorefirebase-d4d75',
    storageBucket: 'tstorefirebase-d4d75.appspot.com',
    androidClientId: '1085587191214-krj853hg2tutradash8gu387sgtlg4ba.apps.googleusercontent.com',
    iosClientId: '1085587191214-9hpuabucq5i97bpp47vjtl6gd7eff3qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore.RunnerTests',
  );
}
