import 'package:flutter/material.dart';
import '../../../../core/utils/formatters/egyptian_formatters.dart';
import '../../domain/models.dart';

const souqGreen=Color(0xFF086A4B),souqGold=Color(0xFFF5B700),souqBg=Color(0xFFF7F8F4);

class LoadingView extends StatelessWidget{final String text;const LoadingView({super.key,this.text='جاري التحميل...'});@override Widget build(BuildContext context)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const CircularProgressIndicator(),const SizedBox(height:12),Text(text)]));}
class EmptyView extends StatelessWidget{final IconData icon;final String title,subtitle;final VoidCallback? onRetry;const EmptyView({super.key,required this.icon,required this.title,required this.subtitle,this.onRetry});@override Widget build(BuildContext context)=>Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:64,color:Colors.grey.shade400),const SizedBox(height:12),Text(title,style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:6),Text(subtitle,textAlign:TextAlign.center,style:TextStyle(color:Colors.grey.shade600)),if(onRetry!=null)...[const SizedBox(height:16),FilledButton.icon(onPressed:onRetry,icon:const Icon(Icons.refresh),label:const Text('إعادة المحاولة'))]])));}
class PriceText extends StatelessWidget{final num value;final TextStyle? style;const PriceText(this.value,{super.key,this.style});@override Widget build(BuildContext context)=>Text(EgyptianFormatters.money(value),style:style??const TextStyle(fontWeight:FontWeight.bold,color:souqGreen));}
class SectionTitle extends StatelessWidget{final String title;final VoidCallback? onTap;const SectionTitle(this.title,{super.key,this.onTap});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.fromLTRB(16,18,16,8),child:Row(children:[Expanded(child:Text(title,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold))),if(onTap!=null)TextButton(onPressed:onTap,child:const Text('عرض الكل'))]));}
class StoreCard extends StatelessWidget{final StoreData store;final VoidCallback onTap;const StoreCard({super.key,required this.store,required this.onTap});@override Widget build(BuildContext context)=>Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:6),clipBehavior:Clip.antiAlias,child:InkWell(onTap:onTap,child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[CircleAvatar(radius:28,backgroundColor:souqGreen.withValues(alpha:.1),child:const Icon(Icons.storefront,color:souqGreen,size:30)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(store.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16))),Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:3),decoration:BoxDecoration(color:(store.isOpen?Colors.green:Colors.red).withValues(alpha:.1),borderRadius:BorderRadius.circular(12)),child:Text(store.isOpen?'مفتوح':'مغلق',style:TextStyle(color:store.isOpen?Colors.green:Colors.red,fontSize:11)))]),const SizedBox(height:4),Text(store.description,maxLines:1,overflow:TextOverflow.ellipsis),const SizedBox(height:6),Wrap(spacing:12,children:[Text('⭐ ${store.rating} (${store.ratingsCount})'),Text('🛵 ${store.deliveryMinutes} دقيقة'),Text('${store.deliveryFee.toStringAsFixed(0)} ج.م توصيل')])]))]))));}

String orderStatusText(OrderStatus s)=>switch(s){OrderStatus.pending=>'جديد',OrderStatus.accepted=>'تم القبول',OrderStatus.preparing=>'قيد التجهيز',OrderStatus.ready=>'جاهز',OrderStatus.outForDelivery=>'خرج للتوصيل',OrderStatus.delivered=>'تم التوصيل',OrderStatus.cancelled=>'ملغي',OrderStatus.rejected=>'مرفوض'};
Color orderStatusColor(OrderStatus s)=>switch(s){OrderStatus.delivered=>Colors.green,OrderStatus.cancelled||OrderStatus.rejected=>Colors.red,OrderStatus.pending=>Colors.orange,_=>Colors.blue};

String? validateName(String? v)=>v==null||v.trim().length<3?'اكتب الاسم كاملًا':null;
String? validateEmail(String? v)=>v==null||!RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$').hasMatch(v.trim())?'اكتب بريدًا إلكترونيًا صحيحًا':null;
String? validatePhone(String? v)=>EgyptianFormatters.normalizeMobile(v??'')==null?'اكتب رقم موبايل مصري صحيحًا':null;
String? validatePassword(String? v)=>v==null||v.length<6?'كلمة المرور 6 أحرف على الأقل':null;
